### ISSUE TITLE
DATABASE_URL check failing

### ISSUE THREAD

**Issue by trevormerritt** [kingsquare/mediawiki-dokku#1]
When deploying mediawiki-dokku, the mediawiki entrypoint doesn't see DATABASE_URL

Is there something I'm missing?  I'll update the docs and submit a PR.  :)

tmerritt@trevdev:~/Projects/mediawiki-dokku$ git push dokku-test
<OUTPUT SNIPPED>
=====> dokku web container output:
       "DATABASE_URL is not set.. have you linked the database?" && exit -1
       Trying custom entrypoint script...
       Executing main entrypoint script...
       error: missing MEDIAWIKI_DB_HOST environment variable
        Did you forget to --link your database?
       "DATABASE_URL is not set.. have you linked the database?" && exit -1
       Trying custom entrypoint script...
       Executing main entrypoint script...
       error: missing MEDIAWIKI_DB_HOST environment variable
        Did you forget to --link your database?
       "DATABASE_URL is not set.. have you linked the database?" && exit -1
       Trying custom entrypoint script...
       Executing main entrypoint script...
       error: missing MEDIAWIKI_DB_HOST environment variable
        Did you forget to --link your database?
       "DATABASE_URL is not set.. have you linked the database?" && exit -1
       Trying custom entrypoint script...
       Executing main entrypoint script...
       error: missing MEDIAWIKI_DB_HOST environment variable
        Did you forget to --link your database?
       "DATABASE_URL is not set.. have you linked the database?" && exit -1
       Trying custom entrypoint script...
       Executing main entrypoint script...
       error: missing MEDIAWIKI_DB_HOST environment variable
        Did you forget to --link your database?
       "DATABASE_URL is not set.. have you linked the database?" && exit -1
       Trying custom entrypoint script...
       Executing main entrypoint script...
       error: missing MEDIAWIKI_DB_HOST environment variable
        Did you forget to --link your database?
       "DATABASE_URL is not set.. have you linked the database?" && exit -1
       Trying custom entrypoint script...
       Executing main entrypoint script...
       error: missing MEDIAWIKI_DB_HOST environment variable
        Did you forget to --link your database?
=====> end dokku web container output
To dokku@localhost:dokku
 ! [remote rejected] master -> master (pre-receive hook declined)
tmerritt@trevdev:~/Projects/mediawiki-dokku$ dokku mariadb:info mediawiki                                                                                         =====> Container Information
       Config dir:          /var/lib/dokku/services/mariadb/mediawiki/config
       Data dir:            /var/lib/dokku/services/mariadb/mediawiki/data
       Dsn:                 mysql://mariadb:5be6f82cbdaf62ab@dokku-mariadb-mediawiki:3306/mediawiki
       Exposed ports:       -
       Id:                  9b296a6e10fad4771d3745f105f469771baed9932814657cd4fd00558fa55d53
       Internal ip:         172.17.0.4
       Links:               mediawiki
       Service root:        /var/lib/dokku/services/mariadb/mediawiki
       Status:              running
       Version:             mariadb:10.3.0
tmerritt@trevdev:~/Projects/mediawiki-dokku$ dokku mariadb:linked mediawiki mediawiki
-----> Service mediawiki is linked to mediawiki
tmerritt@trevdev:~/Projects/mediawiki-dokku$ dokku config mediawiki
=====> mediawiki env vars
DOKKU_APP_TYPE:  herokuish
environment:     production
DATABASE_URL:    mysql://mariadb:5be6f82cbdaf62ab@dokku-mariadb-mediawiki:3306/mediawiki

**Comment by trevormerritt** [comment]
> 
> tmerritt@trevdev:~/Projects/mediawiki-dokku$ git push dokku-test
> <OUTPUT SNIPPED>
> =====> dokku web container output:
>        "DATABASE_URL is not set.. have you linked the database?" && exit -1
>        Trying custom entrypoint script...
>        Executing main entrypoint script...
>        error: missing MEDIAWIKI_DB_HOST environment variable
>         Did you forget to --link your database?
>        "DATABASE_URL is not set.. have you linked the database?" && exit -1
>        Trying custom entrypoint script...
>        Executing main entrypoint script...
>        error: missing MEDIAWIKI_DB_HOST environment variable
>         Did you forget to --link your database?
>        "DATABASE_URL is not set.. have you linked the database?" && exit -1
>        Trying custom entrypoint script...
>        Executing main entrypoint script...
>        error: missing MEDIAWIKI_DB_HOST environment variable
>         Did you forget to --link your database?
>        "DATABASE_URL is not set.. have you linked the database?" && exit -1
>        Trying custom entrypoint script...
>        Executing main entrypoint script...
>        error: missing MEDIAWIKI_DB_HOST environment variable
>         Did you forget to --link your database?
>        "DATABASE_URL is not set.. have you linked the database?" && exit -1
>        Trying custom entrypoint script...
>        Executing main entrypoint script...
>        error: missing MEDIAWIKI_DB_HOST environment variable
>         Did you forget to --link your database?
>        "DATABASE_URL is not set.. have you linked the database?" && exit -1
>        Trying custom entrypoint script...
>        Executing main entrypoint script...
>        error: missing MEDIAWIKI_DB_HOST environment variable
>         Did you forget to --link your database?
>        "DATABASE_URL is not set.. have you linked the database?" && exit -1
>        Trying custom entrypoint script...
>        Executing main entrypoint script...
>        error: missing MEDIAWIKI_DB_HOST environment variable
>         Did you forget to --link your database?
> =====> end dokku web container output
> To dokku@localhost:dokku
>  ! [remote rejected] master -> master (pre-receive hook declined)
> tmerritt@trevdev:~/Projects/mediawiki-dokku$ dokku mariadb:info mediawiki                                                                                         =====> Container Information
>        Config dir:          /var/lib/dokku/services/mariadb/mediawiki/config
>        Data dir:            /var/lib/dokku/services/mariadb/mediawiki/data
>        Dsn:                 mysql://mariadb:5be6f82cbdaf62ab@dokku-mariadb-mediawiki:3306/mediawiki
>        Exposed ports:       -
>        Id:                  9b296a6e10fad4771d3745f105f469771baed9932814657cd4fd00558fa55d53
>        Internal ip:         172.17.0.4
>        Links:               mediawiki
>        Service root:        /var/lib/dokku/services/mariadb/mediawiki
>        Status:              running
>        Version:             mariadb:10.3.0
> tmerritt@trevdev:~/Projects/mediawiki-dokku$ dokku mariadb:linked mediawiki mediawiki
> -----> Service mediawiki is linked to mediawiki
> tmerritt@trevdev:~/Projects/mediawiki-dokku$ dokku config mediawiki
> =====> mediawiki env vars
> DOKKU_APP_TYPE:  herokuish
> environment:     production
> DATABASE_URL:    mysql://mariadb:5be6f82cbdaf62ab@dokku-mariadb-mediawiki:3306/mediawiki
>

**Comment by AubreyHewes** [comment]
@trevormerritt I assume you fixed your problem? as no PR ;-)
